### ISSUE TITLE
statsd not working with eventlet

### ISSUE THREAD

**Issue by woodsaj** [raintank/graphite-kairosdb#7]
```
Traceback (most recent call last):
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 45, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 93, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/middleware.py", line 46, in __call__
    return self.app(environ, start_response)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/middleware.py", line 15, in __call__
    return self.app(environ, start_response)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/app.py", line 407, in render
    series_list = evaluateTarget(context, target)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/app.py", line 491, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/app.py", line 501, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/app.py", line 511, in evaluateTokens
    arg) for arg in tokens.call.args]
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/app.py", line 501, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return fetchData(requestContext, tokens.pathExpression)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/render/datalib.py", line 157, in fetchData
    return _fetchData(pathExpr, startTime, endTime, requestContext, seriesList)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/render/datalib.py", line 94, in _fetchData
    for node in matching_nodes:
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_api/storage.py", line 21, in find
    for node in finder.find_nodes(query):
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_kairosdb.py", line 120, in find_nodes
    matches = self.search_series(leaf_regex, query)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/graphite_kairosdb.py", line 316, in search_series
    logger.debug('search_series', matches=len(matches))
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/statsd/client.py", line 41, in __exit__
    self.stop()
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/statsd/client.py", line 55, in stop
    self.send()
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/statsd/client.py", line 64, in send
    self.client.timing(self.stat, self.ms, self.rate)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/statsd/client.py", line 85, in timing
    self._send_stat(stat, '%d|ms' % delta, rate)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/statsd/client.py", line 113, in _send_stat
    self._after(self._prepare(stat, value, rate))
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/statsd/client.py", line 128, in _after
    self._send(data)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/statsd/client.py", line 148, in _send
    self._sock.sendto(data.encode('ascii'), self._addr)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 382, in sendto
    self._trampoline(self.fd, write=True)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/eventlet/greenio/base.py", line 201, in _trampoline
    mark_as_closed=self._mark_as_closed)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 160, in trampoline
    listener = hub.add(hub.WRITE, fileno, current.switch, current.throw, mark_as_closed)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 49, in add
    listener = BaseHub.add(self, evtype, fileno, cb, tb, mac)
  File "/usr/share/python/graphite/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 177, in add
    evtype, fileno, evtype, cb, bucket[fileno]))
RuntimeError: Second simultaneous write on fileno 8 detected.  Unless you really know what you're doing, make sure that only one greenthread can write any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want 
to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<built-in method switch of GreenThread object at 0x7fa134876e10>; THAT THREAD=FdListener('write', 8, <built-in method switch of GreenThread object at 0x7fa
1346f7190>, <built-in method throw of GreenThread object at 0x7fa1346f7190>)
```

**Comment by woodsaj** [comment]
A simple workaround for this is to just not use eventlet.  and stick with gunicorn's sync worker class.

**Comment by woodsaj** [comment]
This has been fixed by forking the pystatsd package and making it work with eventlet.

https://github.com/woodsaj/pystatsd
